/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/404': RouteRecordInfo<'/404', '/404', Record<never, never>, Record<never, never>>,
    '/auth': RouteRecordInfo<'/auth', '/auth', Record<never, never>, Record<never, never>>,
    '/auth/login': RouteRecordInfo<'/auth/login', '/auth/login', Record<never, never>, Record<never, never>>,
    '/auth/register': RouteRecordInfo<'/auth/register', '/auth/register', Record<never, never>, Record<never, never>>,
    '/course': RouteRecordInfo<'/course', '/course', Record<never, never>, Record<never, never>>,
    '/grade': RouteRecordInfo<'/grade', '/grade', Record<never, never>, Record<never, never>>,
    '/home': RouteRecordInfo<'/home', '/home', Record<never, never>, Record<never, never>>,
    '/setting': RouteRecordInfo<'/setting', '/setting', Record<never, never>, Record<never, never>>,
    '/student': RouteRecordInfo<'/student', '/student', Record<never, never>, Record<never, never>>,
    'teacher': RouteRecordInfo<'teacher', '/teacher', Record<never, never>, Record<never, never>>,
    '/teacher/arragement': RouteRecordInfo<'/teacher/arragement', '/teacher/arragement', Record<never, never>, Record<never, never>>,
    '/teacher/info': RouteRecordInfo<'/teacher/info', '/teacher/info', Record<never, never>, Record<never, never>>,
  }
}
